name: Deploy Astro site to Main Site
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build with Astro
        run: npx --no-install astro build

      - name: Deploy to Root Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.MY_DEPLOY_TOKEN }}
          external_repository: rdcorona/rdcorona-web
          publish_branch: main
          publish_dir: ./dist
          destination_dir: professional
          keep_files: true
